{% set name = "salabim" %}
{% set version = "25.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/salabim-{{ version }}.tar.gz
  sha256: 8718d12056248f5892db0a036d0e4133dfe057f82c2e0e99c54505c9c8add4ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
  run_constrained:
    - greenlet
    - numpy
    - opencv
    - pandas
    - pillow
    # salabim docs say this stricth pin is needed, but worried that this will
    # be problematic in environment solves
    - pyglet  # ==1.5.27
    - pyopengl
    - pysimplegui
    - python-dateutil
    - scipy
    # no feedstock, but may be added in future
    # - pywavefront

test:
  imports:
    - salabim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

outputs:
  - name: salabim
  - name: salabim-animation
    requirements:
      build:
        - pip
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - salabim
        # all of these are optional dependencies but are needed for the
        # animations
        - numpy
        - opencv
        - pillow
        - pyopengl
        - greenlet
      test:
        requires:
          - python {{ python_min }}
        imports:
          - salabim

about:
  home: https://github.com/salabim/salabim
  summary: discrete event simulation in Python
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - moorepants
