{% set name = "salabim" %}
{% set version = "24.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/salabim-{{ version }}.tar.gz
  sha256: 2a266133ee30be60bfe1b11c1e1755f7379e2df5ad718d58873d72fb62fd695c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
  run_constrained:
    - greenlet
    - numpy
    - opencv
    - pandas
    - pillow
    # salabim docs say this stricth pin is needed, but worried that this will
    # be problematic in environment solves
    - pyglet  # ==1.5.27
    - pyopengl
    - pysimplegui
    - python-dateutil
    - scipy
    # no feedstock, but may be added in future
    # - pywavefront

test:
  imports:
    - salabim
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: salabim
  - name: salabim-animation
    requirements:
      build:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - salabim
        # all of these are optional dependencies but are needed for the
        # animations
        - numpy
        - opencv
        - pillow
        - pyopengl
        - greenlet
      test:
        imports:
          - salabim

about:
  home: https://github.com/salabim/salabim
  summary: discrete event simulation in Python
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - moorepants
